### ISSUE TITLE
Cannot mount volume when webhook is enabled

### ISSUE THREAD

**Issue by uprush** [kubeflow/spark-operator#1000]
I got the below error when submitting a simple Spark app which mounts volumes. This error only occurred after reinstalling the operator with webhook enabled (--set enableWebhook=true).

```
  volumes:
    - name: "staging-vol"
      persistentVolumeClaim:
        claimName: spark-staging
    - name: local-vol
      emptyDir: {}
  driver:
    cores: 1
    coreLimit: "1200m"
    memory: "512m"
    volumeMounts:
      - name: "staging-vol"
        mountPath: "/home/spark/staging"
      - name: "local-vol"
        mountPath: "/home/spark/local"
```

```
kubectl describe SparkApplication doglover

Exception in thread "main" io.fabric8.kubernetes.client.KubernetesClientException: Failure executing: POST at: https://10.96.0.1/api/v1/namespaces/default/pods. Message: Pod "doglover-driver" is invalid: spec.containers[0].volumeMounts[4].mountPath: Invalid value: "/home/spark/local": must be unique. Received status: Status(apiVersion=v1, code=422, details=StatusDetails(causes=[StatusCause(field=spec.containers[0].volumeMounts[4].mountPath, message=Invalid value: "/home/spark/local": must be unique, reason=FieldValueInvalid, additionalProperties={})], group=null, kind=Pod, name=doglover-driver, retryAfterSeconds=null, uid=null, additionalProperties={}), kind=Status, message=Pod "doglover-driver" is invalid: spec.containers[0].volumeMounts[4].mountPath: Invalid value: "/home/spark/local": must be unique, metadata=ListMeta(_continue=null, remainingItemCount=null, resourceVersion=null, selfLink=null, additionalProperties={}), reason=Invalid, status=Failure, additionalProperties={}).
  at io.fabric8.kubernetes.client.dsl.base.OperationSupport.requestFailure(OperationSupport.java:568)
  at io.fabric8.kubernetes.client.dsl.base.OperationSupport.assertResponseCode(OperationSupport.java:507)
  at io.fabric8.kubernetes.client.dsl.base.OperationSupport.handleResponse(OperationSupport.java:471)
  at io.fabric8.kubernetes.client.dsl.base.OperationSupport.handleResponse(OperationSupport.java:430)
  at io.fabric8.kubernetes.client.dsl.base.OperationSupport.handleCreate(OperationSupport.java:251)
  at io.fabric8.kubernetes.client.dsl.base.BaseOperation.handleCreate(BaseOperation.java:815)
  at io.fabric8.kubernetes.client.dsl.base.BaseOperation.create(BaseOperation.java:333)
  at org.apache.spark.deploy.k8s.submit.Client.$anonfun$run$2(KubernetesClientApplication.scala:130)
  at org.apache.spark.deploy.k8s.submit.Client.$anonfun$run$2$adapted(KubernetesClientApplication.scala:129)
  at org.apache.spark.util.Utils$.tryWithResource(Utils.scala:2539)
  at org.apache.spark.deploy.k8s.submit.Client.run(KubernetesClientApplication.scala:129)
  at org.apache.spark.deploy.k8s.submit.KubernetesClientApplication.$anonfun$run$4(KubernetesClientApplication.scala:221)
  at org.apache.spark.deploy.k8s.submit.KubernetesClientApplication.$anonfun$run$4$adapted(KubernetesClientApplication.scala:215)
  at org.apache.spark.util.Utils$.tryWithResource(Utils.scala:2539)
  at org.apache.spark.deploy.k8s.submit.KubernetesClientApplication.run(KubernetesClientApplication.scala:215)
  at org.apache.spark.deploy.k8s.submit.KubernetesClientApplication.start(KubernetesClientApplication.scala:188)
  at org.apache.spark.deploy.SparkSubmit.org$apache$spark$deploy$SparkSubmit$$runMain(SparkSubmit.scala:928)
  at org.apache.spark.deploy.SparkSubmit.doRunMain$1(SparkSubmit.scala:180)
  at org.apache.spark.deploy.SparkSubmit.submit(SparkSubmit.scala:203)
  at org.apache.spark.deploy.SparkSubmit.doSubmit(SparkSubmit.scala:90)
  at org.apache.spark.deploy.SparkSubmit$$anon$2.doSubmit(SparkSubmit.scala:1007)
  at org.apache.spark.deploy.SparkSubmit$.main(SparkSubmit.scala:1016)
  at org.apache.spark.deploy.SparkSubmit.main(SparkSubmit.scala)
20/08/19 03:35:14 INFO ShutdownHookManager: Shutdown hook called
```

**Comment by uprush** [comment]
I am using the latest operator.
```
NAME          	NAMESPACE	REVISION	UPDATED                                	STATUS  	CHART              	APP VERSION
spark-operator	operator 	1       	2020-08-19 03:51:11.141747955 +0000 UTC	deployed	sparkoperator-0.8.2	v1beta2-1.2.0-3.0.0
```
