### ISSUE TITLE
spark executors keeps getting killed with exit code 1 and doesn't get restarted

### ISSUE THREAD

**Issue by shensonj** [kubeflow/spark-operator#1019]
@liyinan926 

We are using v1beta2-1.1.2-2.4.5 version of operator with spark-2.4.4

spark executors keeps getting killed with exit code 1 and we are seeing following exception in the executor which goes to error state. Once this error happens, driver doesn't restart executor. Any configuration available in operator to manage executor failures? Any idea if this issue will be fixed once we upgrade to spark-3.0.0/spark operator version 3.0.0?

Exception in thread "main" java.lang.reflect.UndeclaredThrowableException
	at org.apache.hadoop.security.UserGroupInformation.doAs(UserGroupInformation.java:1713)
	at org.apache.spark.deploy.SparkHadoopUtil.runAsSparkUser(SparkHadoopUtil.scala:64)
	at org.apache.spark.executor.CoarseGrainedExecutorBackend$.run(CoarseGrainedExecutorBackend.scala:188)
	at org.apache.spark.executor.CoarseGrainedExecutorBackend$.main(CoarseGrainedExecutorBackend.scala:281)
	at org.apache.spark.executor.CoarseGrainedExecutorBackend.main(CoarseGrainedExecutorBackend.scala)
Caused by: org.apache.spark.SparkException: Exception thrown in awaitResult: 
	at org.apache.spark.util.ThreadUtils$.awaitResult(ThreadUtils.scala:226)
	at org.apache.spark.rpc.RpcTimeout.awaitResult(RpcTimeout.scala:75)
	at org.apache.spark.rpc.RpcEnv.setupEndpointRefByURI(RpcEnv.scala:101)
	at org.apache.spark.executor.CoarseGrainedExecutorBackend$$anonfun$run$1.apply$mcV$sp(CoarseGrainedExecutorBackend.scala:201)
	at org.apache.spark.deploy.SparkHadoopUtil$$anon$2.run(SparkHadoopUtil.scala:65)
	at org.apache.spark.deploy.SparkHadoopUtil$$anon$2.run(SparkHadoopUtil.scala:64)
	at java.security.AccessController.doPrivileged(Native Method)
	at javax.security.auth.Subject.doAs(Subject.java:422)
	at org.apache.hadoop.security.UserGroupInformation.doAs(UserGroupInformation.java:1698)
	... 4 more
Caused by: java.io.IOException: Failed to connect to act-pipeline-app-1600187491917-driver-svc.default.svc:7078
	at org.apache.spark.network.client.TransportClientFactory.createClient(TransportClientFactory.java:245)
	at org.apache.spark.network.client.TransportClientFactory.createClient(TransportClientFactory.java:187)
	at org.apache.spark.rpc.netty.NettyRpcEnv.createClient(NettyRpcEnv.scala:198)
	at org.apache.spark.rpc.netty.Outbox$$anon$1.call(Outbox.scala:194)
	at org.apache.spark.rpc.netty.Outbox$$anon$1.call(Outbox.scala:190)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
Caused by: java.net.UnknownHostException: act-pipeline-app-1600187491917-driver-svc.default.svc
	at java.net.InetAddress.getAllByName0(InetAddress.java:1281)
	at java.net.InetAddress.getAllByName(InetAddress.java:1193)
	at java.net.InetAddress.getAllByName(InetAddress.java:1127)
	at java.net.InetAddress.getByName(InetAddress.java:1077)
	at io.netty.util.internal.SocketUtils$8.run(SocketUtils.java:146)
	at io.netty.util.internal.SocketUtils$8.run(SocketUtils.java:143)
	at java.security.AccessController.doPrivileged(Native Method)
	at io.netty.util.internal.SocketUtils.addressByName(SocketUtils.java:143)
	at io.netty.resolver.DefaultNameResolver.doResolve(DefaultNameResolver.java:43)
	at io.netty.resolver.SimpleNameResolver.resolve(SimpleNameResolver.java:63)
	at io.netty.resolver.SimpleNameResolver.resolve(SimpleNameResolver.java:55)
	at io.netty.resolver.InetSocketAddressResolver.doResolve(InetSocketAddressResolver.java:57)
	at io.netty.resolver.InetSocketAddressResolver.doResolve(InetSocketAddressResolver.java:32)
	at io.netty.resolver.AbstractAddressResolver.resolve(AbstractAddressResolver.java:108)
	at io.netty.bootstrap.Bootstrap.doResolveAndConnect0(Bootstrap.java:208)
	at io.netty.bootstrap.Bootstrap.access$000(Bootstrap.java:49)
	at io.netty.bootstrap.Bootstrap$1.operationComplete(Bootstrap.java:188)
	at io.netty.bootstrap.Bootstrap$1.operationComplete(Bootstrap.java:174)
	at io.netty.util.concurrent.DefaultPromise.notifyListener0(DefaultPromise.java:507)
	at io.netty.util.concurrent.DefaultPromise.notifyListenersNow(DefaultPromise.java:481)
	at io.netty.util.concurrent.DefaultPromise.notifyListeners(DefaultPromise.java:420)
	at io.netty.util.concurrent.DefaultPromise.trySuccess(DefaultPromise.java:104)
	at io.netty.channel.DefaultChannelPromise.trySuccess(DefaultChannelPromise.java:82)
	at io.netty.channel.AbstractChannel$AbstractUnsafe.safeSetSuccess(AbstractChannel.java:978)
	at io.netty.channel.AbstractChannel$AbstractUnsafe.register0(AbstractChannel.java:512)
	at io.netty.channel.AbstractChannel$AbstractUnsafe.access$200(AbstractChannel.java:423)
	at io.netty.channel.AbstractChannel$AbstractUnsafe$1.run(AbstractChannel.java:482)
	at io.netty.util.concurrent.AbstractEventExecutor.safeExecute(AbstractEventExecutor.java:163)
	at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:403)
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:463)
	at io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:858)
	at io.netty.util.concurrent.DefaultThreadFactory$DefaultRunnableDecorator.run(DefaultThreadFactory.java:138)
	... 1 more
CodeCache: size=245760Kb used=4762Kb max_used=4763Kb free=240997Kb
 bounds [0x00007f49f5000000, 0x00007f49f54b0000, 0x00007f4a04000000]
 total_blobs=1764 nmethods=1356 adapters=324
 compilation: enabled

**Comment by tfasanga** [comment]
Additional information:

The status of spark application shows it is RUNNING:
```
kubectl describe sparkapplications.sparkoperator.k8s.io act-pipeline-app
...
...
Status:
  Application State:
    State:  RUNNING
  Driver Info:
    Pod Name:             act-pipeline-app-driver
    Web UI Address:       10.233.57.201:40550
    Web UI Port:          40550
    Web UI Service Name:  act-pipeline-app-ui-svc
  Execution Attempts:     1
  Executor State:
    act-pipeline-app-1600097064694-exec-1:  RUNNING
  Last Submission Attempt Time:             2020-09-14T15:24:26Z
  Spark Application Id:                     spark-942bb2e500c54f92ac357b818c712558
  Submission Attempts:                      1
  Submission ID:                            4ecdb6ca-d237-4524-b05e-c42cfcc73dc7
  Termination Time:                         <nil>
Events:                                     <none>
```

The executor pod is reporting that it is Terminated:
```
kubectl describe pod -l sparkoperator.k8s.io/app-name=act-pipeline-app,spark-role=executor
...
...
Containers:
  executor:
    Container ID:  docker://9aa5b585e8fb7390b87a4771f3ed1402cae41f0fe55905d0172ed6e90dde34e6
...
    Ports:         7079/TCP, 8090/TCP
    Host Ports:    0/TCP, 0/TCP
    Args:
      executor
    State:          Terminated
      Reason:       Error
      Exit Code:    1
      Started:      Mon, 14 Sep 2020 11:25:35 -0400
      Finished:     Mon, 14 Sep 2020 11:25:39 -0400
    Ready:          False
    Restart Count:  0
...
Conditions:
  Type              Status
  Initialized       True 
  Ready             False 
  ContainersReady   False 
  PodScheduled      True 
...
QoS Class:       Burstable
Node-Selectors:  <none>
Tolerations:     node.kubernetes.io/not-ready:NoExecute for 300s
                 node.kubernetes.io/unreachable:NoExecute for 300s
Events:          <none>
```

**Comment by shensonj** [comment]
@liyinan926  Is this issue related to https://issues.apache.org/jira/browse/SPARK-24135

**Comment by tfasanga** [comment]
This is not related to issue https://issues.apache.org/jira/browse/SPARK-24135.
This problem is a transient problem, it does not happen always, suggesting that it is sensitive to timing. It seems to occur when the k8s system is busy with launching other PODs (multiple helm charts are being installed), so there may be a slight delay between starting the driver and starting the driver's service (act-pipeline-app-1600187491917-driver-svc.default.svc) that executor needs to resolve during its initialization.

The executor simply fails because the driver's k8 service is not available at the time when executor starts (Executor exception cause in the log shows: "java.net.UnknownHostException: act-pipeline-app-1600187491917-driver-svc.default.svc).
After this happens I can check that the service is available that indicates that it is running and it was a transient condition only.

This would all normal because there might be delays in activating/resolving the service, and it is expected that executor POD is terminated in this case (due to exception).

It expected that the executor is restarted after this, but it is not happening.

**Comment by tfasanga** [comment]
I compared the spark operator logs of the success and failed scenarios. There is difference of first mentioning the executor POD in the log (line `"Pod act-pipeline-app-________-exec-1 in namespace default is subject to mutation")`
This is just showing that the timing in these cases is different.
In both situations the driver and executor are started, but in failed case the executor terminates due to exception and it is not restarted by driver.
 
In **success** case the executor pod message comes AFTER the Spark application (driver) is **RUNNING**:

```
...
I0914 12:46:28.408910       9 controller.go:773] Update the status of SparkApplication default/act-pipeline-app from:
{
  "sparkApplicationId": "spark-5a82c777346a4e4cb959bf6fe1564d7e",
  "submissionID": "c7946b13-2348-448c-a194-e3e7dbb9a859",
  "lastSubmissionAttemptTime": "2020-09-14T12:46:12Z",
  "terminationTime": null,
  "driverInfo": {
    "webUIServiceName": "act-pipeline-app-ui-svc",
    "webUIPort": 40550,
    "webUIAddress": "10.233.37.34:40550",
    "podName": "act-pipeline-app-driver"
  },
  "applicationState": {
    "state": "SUBMITTED"
  },
  "executionAttempts": 1,
  "submissionAttempts": 1
}
to:
{
  "sparkApplicationId": "spark-5a82c777346a4e4cb959bf6fe1564d7e",
  "submissionID": "c7946b13-2348-448c-a194-e3e7dbb9a859",
  "lastSubmissionAttemptTime": "2020-09-14T12:46:12Z",
  "terminationTime": null,
  "driverInfo": {
    "webUIServiceName": "act-pipeline-app-ui-svc",
    "webUIPort": 40550,
    "webUIAddress": "10.233.37.34:40550",
    "podName": "act-pipeline-app-driver"
  },
  "applicationState": {
    "state": "RUNNING"
  },
  "executionAttempts": 1,
  "submissionAttempts": 1
}
...
I0914 12:46:31.454641       9 webhook.go:556] Pod act-pipeline-app-1600087571105-exec-1 in namespace default is subject to mutation
```

In **failed** case the the executor pod message comes AFTER the Spark application (driver) is **SUBMITTED** :
```
...
I0914 15:24:26.752041       9 controller.go:773] Update the status of SparkApplication default/act-pipeline-app from:
{
  "submissionID": "4ecdb6ca-d237-4524-b05e-c42cfcc73dc7",
  "lastSubmissionAttemptTime": "2020-09-14T15:24:26Z",
  "terminationTime": null,
  "driverInfo": {
    "webUIServiceName": "act-pipeline-app-ui-svc",
    "webUIPort": 40550,
    "webUIAddress": "10.233.57.201:40550",
    "podName": "act-pipeline-app-driver"
  },
  "applicationState": {
    "state": "SUBMITTED"
  },
  "executionAttempts": 1,
  "submissionAttempts": 1
}
to:
{
  "sparkApplicationId": "spark-942bb2e500c54f92ac357b818c712558",
  "submissionID": "4ecdb6ca-d237-4524-b05e-c42cfcc73dc7",
  "lastSubmissionAttemptTime": "2020-09-14T15:24:26Z",
  "terminationTime": null,
  "driverInfo": {
    "webUIServiceName": "act-pipeline-app-ui-svc",
    "webUIPort": 40550,
    "webUIAddress": "10.233.57.201:40550",
    "podName": "act-pipeline-app-driver"
  },
  "applicationState": {
    "state": "SUBMITTED"
  },
  "executionAttempts": 1,
  "submissionAttempts": 1
}
...
I0914 15:25:26.732065       9 webhook.go:556] Pod act-pipeline-app-1600097064694-exec-1 in namespace default is subject to mutation
...
```

**Comment by amitme10** [comment]
Hey , got this issue as well at my Streaming job , what's the solution here?

**Comment by SandishKumarHN** [comment]
@tfasanga I see similar issue but I clearly see driver svc clsterIp is not been attached 

` kubectl describe svc spark-pi-ui-svc -n optik-ae
Name:              spark-pi-ui-svc
Namespace:         optik-ae
Labels:            sparkoperator.k8s.io/app-name=spark-pi
                   sparkoperator.k8s.io/submission-id=49d67c2f-3166-4ce3-aa4a-3058baa2108e
Annotations:       <none>
Selector:          spark-role=driver,sparkoperator.k8s.io/app-name=spark-pi
Type:              ClusterIP
IP:                10.3.2.245
Port:              spark-driver-ui-port  4040/TCP
TargetPort:        4040/TCP
Endpoints:         10.2.174.72:4040
Session Affinity:  None
Events:            <none>
kubectl describe svc spark-pi-1610000110552-driver-svc -n optik-ae
Name:              spark-pi-1610000110552-driver-svc
Namespace:         optik-ae
Labels:            <none>
Annotations:       <none>
Selector:          spark-app-selector=spark-7554d84c993644f6b2838ac0c2fd5431,spark-role=driver,sparkoperator.k8s.io/app-name=spark-pi,sparkoperator.k8s.io/launched-by-spark-operator=true,sparkoperator.k8s.io/submission-id=49d67c2f-3166-4ce3-aa4a-3058baa2108e,version=2.4.5
Type:              ClusterIP
IP:                None
Port:              driver-rpc-port  7078/TCP
TargetPort:        7078/TCP
Endpoints:         10.2.174.72:7078
Port:              blockmanager  7079/TCP
TargetPort:        7079/TCP
Endpoints:         10.2.174.72:7079
Session Affinity:  None
Events:            <none>`

Error:

`21/01/07 06:15:30 INFO SecurityManager: SecurityManager: authentication disabled; ui acls disabled; users  with view permissions: Set(root); groups with view permissions: Set(); users  with modify permissions: Set(root); groups with modify permissions: Set()
Exception in thread "main" java.lang.reflect.UndeclaredThrowableException
	at org.apache.hadoop.security.UserGroupInformation.doAs(UserGroupInformation.java:1713)
	at org.apache.spark.deploy.SparkHadoopUtil.runAsSparkUser(SparkHadoopUtil.scala:64)
	at org.apache.spark.executor.CoarseGrainedExecutorBackend$.run(CoarseGrainedExecutorBackend.scala:188)
	at org.apache.spark.executor.CoarseGrainedExecutorBackend$.main(CoarseGrainedExecutorBackend.scala:285)
	at org.apache.spark.executor.CoarseGrainedExecutorBackend.main(CoarseGrainedExecutorBackend.scala)
Caused by: org.apache.spark.SparkException: Exception thrown in awaitResult: 
	at org.apache.spark.util.ThreadUtils$.awaitResult(ThreadUtils.scala:226)
	at org.apache.spark.rpc.RpcTimeout.awaitResult(RpcTimeout.scala:75)
	at org.apache.spark.rpc.RpcEnv.setupEndpointRefByURI(RpcEnv.scala:101)
	at org.apache.spark.executor.CoarseGrainedExecutorBackend$$anonfun$run$1.apply$mcV$sp(CoarseGrainedExecutorBackend.scala:201)
	at org.apache.spark.deploy.SparkHadoopUtil$$anon$2.run(SparkHadoopUtil.scala:65)
	at org.apache.spark.deploy.SparkHadoopUtil$$anon$2.run(SparkHadoopUtil.scala:64)
	at java.security.AccessController.doPrivileged(Native Method)
	at javax.security.auth.Subject.doAs(Subject.java:422)
	at org.apache.hadoop.security.UserGroupInformation.doAs(UserGroupInformation.java:1698)
	... 4 more
Caused by: java.io.IOException: Failed to connect to spark-pi-1610000110552-driver-svc.optik-ae.svc:7078
	at org.apache.spark.network.client.TransportClientFactory.createClient(TransportClientFactory.java:245)
	at org.apache.spark.network.client.TransportClientFactory.createClient(TransportClientFactory.java:187)
	at org.apache.spark.rpc.netty.NettyRpcEnv.createClient(NettyRpcEnv.scala:198)
	at org.apache.spark.rpc.netty.Outbox$$anon$1.call(Outbox.scala:194)
	at org.apache.spark.rpc.netty.Outbox$$anon$1.call(Outbox.scala:190)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
Caused by: java.net.UnknownHostException: spark-pi-1610000110552-driver-svc.optik-ae.svc
	at java.net.InetAddress.getAllByName0(InetAddress.java:1281)
	at java.net.InetAddress.getAllByName(InetAddress.java:1193)
	at java.net.InetAddress.getAllByName(InetAddress.java:1127)
	at java.net.InetAddress.getByName(InetAddress.java:1077)
	at io.netty.util.internal.SocketUtils$8.run(SocketUtils.java:146)
	at io.netty.util.internal.SocketUtils$8.run(SocketUtils.java:143)
	at java.security.AccessController.doPrivileged(Native Method)
	at io.netty.util.internal.SocketUtils.addressByName(SocketUtils.java:143)
	at io.netty.resolver.DefaultNameResolver.doResolve(DefaultNameResolver.java:43)
	at io.netty.resolver.SimpleNameResolver.resolve(SimpleNameResolver.java:63)
	at io.netty.resolver.SimpleNameResolver.resolve(SimpleNameResolver.java:55)
	at io.netty.resolver.InetSocketAddressResolver.doResolve(InetSocketAddressResolver.java:57)
	at io.netty.resolver.InetSocketAddressResolver.doResolve(InetSocketAddressResolver.java:32)
	at io.netty.resolver.AbstractAddressResolver.resolve(AbstractAddressResolver.java:108)
	at io.netty.bootstrap.Bootstrap.doResolveAndConnect0(Bootstrap.java:202)
	at io.netty.bootstrap.Bootstrap.access$000(Bootstrap.java:48)
	at io.netty.bootstrap.Bootstrap$1.operationComplete(Bootstrap.java:182)
	at io.netty.bootstrap.Bootstrap$1.operationComplete(Bootstrap.java:168)
	at io.netty.util.concurrent.DefaultPromise.notifyListener0(DefaultPromise.java:577)
	at io.netty.util.concurrent.DefaultPromise.notifyListenersNow(DefaultPromise.java:551)
	at io.netty.util.concurrent.DefaultPromise.notifyListeners(DefaultPromise.java:490)
	at io.netty.util.concurrent.DefaultPromise.setValue0(DefaultPromise.java:615)
	at io.netty.util.concurrent.DefaultPromise.setSuccess0(DefaultPromise.java:604)
	at io.netty.util.concurrent.DefaultPromise.trySuccess(DefaultPromise.java:104)
	at io.netty.channel.DefaultChannelPromise.trySuccess(DefaultChannelPromise.java:84)
	at io.netty.channel.AbstractChannel$AbstractUnsafe.safeSetSuccess(AbstractChannel.java:985)
	at io.netty.channel.AbstractChannel$AbstractUnsafe.register0(AbstractChannel.java:505)
	at io.netty.channel.AbstractChannel$AbstractUnsafe.access$200(AbstractChannel.java:416)
	at io.netty.channel.AbstractChannel$AbstractUnsafe$1.run(AbstractChannel.java:475)
	at io.netty.util.concurrent.AbstractEventExecutor.safeExecute(AbstractEventExecutor.java:163)
	at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:510)
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:518)
	at io.netty.util.concurrent.SingleThreadEventExecutor$6.run(SingleThreadEventExecutor.java:1044)
	at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
	... 1 more
`

**Comment by SandishKumarHN** [comment]
we had an istio enabled on our k8s after adding this annotation everything started working 
"sidecar.istio.io/inject"] = "false"

**Comment by pwzhong** [comment]
@SandishKumarHN I got the same error. Could you please explain more about where to add this annotation? There are a lot istio related deployments on my k8s, is that istio-policy or istio-sidecar-injection? And I see "sidecar.istio.io/inject" has been set to false there.

**Comment by SandishKumarHN** [comment]
@pwzhong just make sure all deployment files are set to "sidecar.istio.io/inject" = "false" and make sure you run the same image version k8s spark operator and spark jobs specs.
