### ISSUE TITLE
NPE while running Spark 3.1.0

### ISSUE THREAD

**Issue by zzvara** [kubeflow/spark-operator#1125]
Operator deployed using:

```
apiVersion: helm.fluxcd.io/v1
kind: HelmRelease
metadata:
  name: google-spark-operator
  namespace: kube-system
spec:
  chart:
    repository: https://googlecloudplatform.github.io/spark-on-k8s-operator
    name: spark-operator
    version: 1.0.5
  releaseName: google-spark-operator
  values:
    logLevel: 3
    sparkJobNamespace: production
    metrics:
      enable: false
    resyncInterval: 10
    webhook:
      enable: true
```

Driver logs periodically:

```
2021-01-11 10:29:37 ERROR Utils:94 - Uncaught exception in thread kubernetes-executor-pod-polling-sync
java.lang.NullPointerException
	at org.apache.spark.scheduler.cluster.k8s.ExecutorPodsSnapshot$.toState(ExecutorPodsSnapshot.scala:89)
	at org.apache.spark.scheduler.cluster.k8s.ExecutorPodsSnapshot$.$anonfun$toStatesByExecutorId$1(ExecutorPodsSnapshot.scala:62)
	at scala.collection.TraversableLike.$anonfun$map$1(TraversableLike.scala:285)
	at scala.collection.Iterator.foreach(Iterator.scala:943)
	at scala.collection.Iterator.foreach$(Iterator.scala:943)
	at scala.collection.AbstractIterator.foreach(Iterator.scala:1431)
	at scala.collection.IterableLike.foreach(IterableLike.scala:74)
	at scala.collection.IterableLike.foreach$(IterableLike.scala:73)
	at scala.collection.AbstractIterable.foreach(Iterable.scala:56)
	at scala.collection.TraversableLike.map(TraversableLike.scala:285)
	at scala.collection.TraversableLike.map$(TraversableLike.scala:278)
	at scala.collection.AbstractTraversable.map(Traversable.scala:108)
	at org.apache.spark.scheduler.cluster.k8s.ExecutorPodsSnapshot$.org$apache$spark$scheduler$cluster$k8s$ExecutorPodsSnapshot$$toStatesByExecutorId(ExecutorPodsSnapshot.scala:61)
	at org.apache.spark.scheduler.cluster.k8s.ExecutorPodsSnapshot$.apply(ExecutorPodsSnapshot.scala:47)
	at org.apache.spark.scheduler.cluster.k8s.ExecutorPodsSnapshotsStoreImpl.replaceSnapshot(ExecutorPodsSnapshotsStoreImpl.scala:102)
	at org.apache.spark.scheduler.cluster.k8s.ExecutorPodsPollingSnapshotSource$PollRunnable.$anonfun$run$1(ExecutorPodsPollingSnapshotSource.scala:62)
	at org.apache.spark.util.Utils$.tryLogNonFatalError(Utils.scala:1419)
	at org.apache.spark.scheduler.cluster.k8s.ExecutorPodsPollingSnapshotSource$PollRunnable.run(ExecutorPodsPollingSnapshotSource.scala:56)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.runAndReset(FutureTask.java:308)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$301(ScheduledThreadPoolExecutor.java:180)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:294)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
```

Executors have weird "test" names:

![image](https://user-images.githubusercontent.com/8371789/104169875-88fdce00-5400-11eb-88c7-25ad415be80c.png)

Streaming job deployed with:

```
apiVersion: "sparkoperator.k8s.io/v1beta2"
kind: SparkApplication
metadata:
  name: job
  namespace: production
spec:
  type: Scala
  mode: cluster
  image: "redacted:443/application/spark:latest"
  imagePullPolicy: Always
  mainClass: redacted.Master
  mainApplicationFile: "local:///opt/spark/dependencies/assembly.jar"
  sparkVersion: "3.1.0"
  hadoopConfigMap: hadoop-default-configuration
  sparkConf:
    "spark.executor.extraJavaOptions": "-XX:ParallelGCThreads=10 -XX:ConcGCThreads=10 -XX:+UseG1GC -XX:InitiatingHeapOccupancyPercent=60 -Dlog4j.configuration=file:///opt/spark/configuration/log4j.properties"
    "spark.driver.extraJavaOptions": "-XX:ParallelGCThreads=10 -XX:ConcGCThreads=10 -XX:+UseG1GC -XX:InitiatingHeapOccupancyPercent=60 -Dlog4j.configuration=file:///opt/spark/configuration/log4j.properties"
    "spark.kubernetes.executor.deleteOnTermination": "false"
    "spark.executor.extraClassPath": "/opt/spark/configuration:/opt/spark/dependencies/assembly.jar"
    "spark.driver.extraClassPath": "/opt/spark/configuration"
    "spark.kubernetes.memoryOverheadFactor": "0.9"
    "spark.serializer": "org.apache.spark.serializer.JavaSerializer"
  restartPolicy:
    type: OnFailure
    onFailureRetries: 10
    onFailureRetryInterval: 10
    onSubmissionFailureRetries: 10
    onSubmissionFailureRetryInterval: 10
  volumes:
    - name: specific-configuration
      configMap:
        name: redacted
    - name: logging-configuration
      configMap:
        name: logging-configuration
  driver:
    cores: 2
    memory: "15000m"
    labels:
      version: 3.1.0
    serviceAccount: google-spark-operator-spark
    env:
      - name: JAVA_HOME
        value: /usr
    volumeMounts:
    - name: specific-configuration
      mountPath: /opt/spark/configuration/redacted.conf
      subPath: redacted.conf
    - name: specific-configuration
      mountPath: /opt/spark/configuration/redacted.conf
      subPath: redacted.conf
    - name: specific-configuration
      mountPath: /opt/spark/configuration/redacted.conf
      subPath: redacted.conf
    - name: logging-configuration
      mountPath: /opt/spark/configuration/log4j.properties
      subPath: log4j.properties
  executor:
    env:
      - name: JAVA_HOME
        value: /usr
    cores: 5
    instances: 4
    memory: "10000m"
    labels:
      version: 3.1.0
    volumeMounts:
    - name: specific-configuration
      mountPath: /opt/spark/configuration/redacted.conf
      subPath: redacted.conf
    - name: specific-configuration
      mountPath: /opt/spark/configuration/redacted.conf
      subPath: redacted.conf
    - name: logging-configuration
      mountPath: /opt/spark/configuration/log4j.properties
      subPath: log4j.properties
    - name: specific-configuration
      mountPath: /opt/spark/configuration/redacted.conf
      subPath: redacted.conf
    affinity:
      nodeAffinity:
        requiredDuringSchedulingIgnoredDuringExecution:
          nodeSelectorTerms:
          - matchExpressions:
            - key: redacted
              operator: In
              values:
              - head
```

**Comment by vvavepacket** [comment]
@zzvara 

Did you build your own "redacted:443/application/spark:latest" that contains spark 3.1.0?

Can you post your dockerfile here for analysis

**Comment by huineng** [comment]
i have the same problem but i think it's purely related to spark 3.1 because if i run my job against a spark 3.0 image it works. against a 3.1 image, i have the problem above. My images are simply compiled using spark build instructions for k8

**Comment by zzvara** [comment]
@vvavepacket @huineng same here, we built Spark 3.1.0 with the stock image (Dockerfile) for K8S.
