### ISSUE TITLE
Application dependency jars stored at hdfs not working

### ISSUE THREAD

**Issue by breetasinha1109** [kubeflow/spark-operator#1182]
Application dependency jars stored at hdfs not working using .spec.deps.jars option field.

Exception thrown -
        at org.apache.hadoop.io.retry.RetryInvocationHandler.invokeMethod(RetryInvocationHandler.java:422)
        at org.apache.hadoop.io.retry.RetryInvocationHandler$Call.invokeMethod(RetryInvocationHandler.java:165)
        at org.apache.hadoop.io.retry.RetryInvocationHandler$Call.invoke(RetryInvocationHandler.java:157)
        at org.apache.hadoop.io.retry.RetryInvocationHandler$Call.invokeOnce(RetryInvocationHandler.java:95)
        at org.apache.hadoop.io.retry.RetryInvocationHandler.invoke(RetryInvocationHandler.java:359)
        at com.sun.proxy.$Proxy29.getFileInfo(Unknown Source)

**Comment by breetasinha1109** [comment]
We are using below spec -

spec:
  hadoopConfigMap: "hadoop-cm"
  deps:
      jars:
         - hdfs://namenodeHA/tmp/phoenix-5.0.0-HBase-2.0-client.jar
         
Hi @liyinan926 ,
Could you please let us know if we are missing any configuration or if its a known issue.

Thanks.

**Comment by breetasinha1109** [comment]
Hi @liyinan926 

Any updates on this?
Thanks.
