### ISSUE TITLE
POD is coming in Running status forever

### ISSUE THREAD

**Issue by connectsachit** [kubeflow/spark-operator#1212]
Can anyone please tell why my pod is not going in completed status?

I have used spark.stop() in my application , still it is not getting stopped . Before reaching spark.stop() itself it is giving WARN Exception
21/03/31 01:21:25 WARN WatchConnectionManager: Exec Failure
java.io.EOFException
        at okio.RealBufferedSource.require(RealBufferedSource.java:61)
        at okio.RealBufferedSource.readByte(RealBufferedSource.java:74)
        at okhttp3.internal.ws.WebSocketReader.readHeader(WebSocketReader.java:117)
        at okhttp3.internal.ws.WebSocketReader.processNextFrame(WebSocketReader.java:101)
        at okhttp3.internal.ws.RealWebSocket.loopReader(RealWebSocket.java:274)
        at okhttp3.internal.ws.RealWebSocket$2.onResponse(RealWebSocket.java:214)
        at okhttp3.RealCall$AsyncCall.execute(RealCall.java:203)
        at okhttp3.internal.NamedRunnable.run(NamedRunnable.java:32)
        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
        at java.base/java.lang.Thread.run(Thread.java:834)

**Comment by jdonnelly-apixio** [comment]
I've hit this issue when engineers haven't closed connections properly (e.g. cassandra, redis, kafka). If you run a sparkctl forward, open the spark ui, go to the executors tab, then you can run thread dumps on the driver and executors and that should help shed some light on the issue. You can also `kubectl exec <pod_name> -it /bin/netstat | grep EST` to help find an established connection to whatever remote host is the culprit. I install netstat on top of the base gcr container tho.
