### ISSUE TITLE
FileNotFoundException prometheus.yaml

### ISSUE THREAD

**Issue by yevsh** [kubeflow/spark-operator#1408]
gcr.io/spark-operator/spark-operator:v1beta2-1.2.0-3.0.0
Spark version: 2.4.5
kubernetes: 1.18.10

in sparkapplication yaml:

```
 monitoring:
    exposeDriverMetrics: true
    exposeExecutorMetrics: true
    prometheus:
      jmxExporterJar: "/opt/spark/jars/jmx_prometheus_javaagent.jar"
      port: 8090
```

from log:

```
 + CMD=("$SPARK_HOME/bin/spark-submit" --conf "spark.driver.bindAddress=$SPARK_DRIVER_BIND_ADDRESS" --deploy-mode client "$@")                 
 + exec /usr/bin/tini -s -- /opt/spark/bin/spark-submit --conf spark.driver.bindAddress=10.244.1.108 --deploy-mode client --properties-file /o 
 Exception in thread "main" java.lang.reflect.InvocationTargetException                                                                        
     at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)                                                                            
     at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)                                                          
     at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)                                                  
     at java.lang.reflect.Method.invoke(Method.java:498)                                                                                       
     at sun.instrument.InstrumentationImpl.loadClassAndStartAgent(InstrumentationImpl.java:386)                                                
     at sun.instrument.InstrumentationImpl.loadClassAndCallPremain(InstrumentationImpl.java:401)                                               
 Caused by: java.io.FileNotFoundException: /etc/metrics/conf/prometheus.yaml (No such file or directory)                                       
     at java.io.FileInputStream.open0(Native Method)    
```
as i understand,  this file created/mounted by spark as **i don’t  have it in image** .
and I know that this file is not required inside the image.

Also it was working...and now not any more, can it be related to cluster roles/serviceaccount/webhook?

please advise.

**Comment by yevsh** [comment]
i am still getting this with spark operator v1beta2-1.3.3-3.1.1

Do I also need to create webhook?
