### ISSUE TITLE
Executor pod failing with error to create temp directory

### ISSUE THREAD

**Issue by abhiramum** [kubeflow/spark-operator#1579]
Hi All,
I am trying sample python application to deploy PVC for every executor. Dynamically created PVC gets mounted to executor pod using SparkOperator but failing to process with error "Failed to create local dir in /tmp/spark-local-dir-1" in pod logs. 

The issue is that the executor pod is running on UID 185 and GID 0 but the mounted PVC is owned by root. Could you please provide some solution to fix this.

Application yaml:

```

apiVersion: sparkoperator.k8s.io/v1beta2
kind: SparkApplication
metadata:
  name: pyspark-pi-test
  namespace: default
spec:
  driver:
    coreLimit: 1200m
    cores: 1
    labels:
      version: 3.1.1
    memory: 512m
    serviceAccount: spark
  executor:
    podSecurityContext:
      fsGroup: 185
    cores: 1
    instances: 1
    memory: 512m
    envVars:
      SPARK_EXECUTOR_DIRS: /tmp/spark-local-dir-1
  image: gcr.io/spark-operator/spark-py:v3.1.1
  imagePullPolicy: Always
  mainApplicationFile: local:///opt/spark/examples/src/main/python/pi.py
  mode: cluster
  pythonVersion: "3"
  sparkConf:
     spark.kubernetes.executor.volumes.persistentVolumeClaim.spark-local-dir-1.options.claimName: "OnDemand"
     spark.kubernetes.executor.volumes.persistentVolumeClaim.spark-local-dir-1.options.storageClass: "gp2"
     spark.kubernetes.executor.volumes.persistentVolumeClaim.spark-local-dir-1.options.sizeLimit: "500Gi"
     spark.kubernetes.executor.volumes.persistentVolumeClaim.spark-local-dir-1.mount.path: "/tmp/spark-local-dir-1"
     spark.kubernetes.executor.volumes.persistentVolumeClaim.spark-local-dir-1.mount.readOnly: "false"
  restartPolicy:
    onFailureRetries: 3
    onFailureRetryInterval: 10
    onSubmissionFailureRetries: 5
    onSubmissionFailureRetryInterval: 20
    type: OnFailure
  sparkVersion: 3.1.1
  type: Python
```

Executor logs:
```
++ id -u
+ myuid=185
++ id -g
+ mygid=0
+ set +e
++ getent passwd 185
+ uidentry=
+ set -e
+ '[' -z '' ']'
+ '[' -w /etc/passwd ']'
+ echo '185:x:185:0:anonymous uid:/opt/spark:/bin/false'
+ SPARK_CLASSPATH=':/opt/spark/jars/*'
+ env
+ grep SPARK_JAVA_OPT_
+ sort -t_ -k4 -n
+ sed 's/[^=]*=\(.*\)/\1/g'
+ readarray -t SPARK_EXECUTOR_JAVA_OPTS
+ '[' -n '' ']'
+ '[' -z ']'
+ '[' -z ']'
+ '[' -n '' ']'
+ '[' -z ']'
+ '[' -z x ']'
+ SPARK_CLASSPATH='/opt/spark/conf::/opt/spark/jars/*'
+ case "$1" in
+ shift 1
+ CMD=(${JAVA_HOME}/bin/java "${SPARK_EXECUTOR_JAVA_OPTS[@]}" -Xms$SPARK_EXECUTOR_MEMORY -Xmx$SPARK_EXECUTOR_MEMORY -cp "$SPARK_CLASSPATH:$SPARK_DIST_CLASSPATH" org.apache.spark.executor.CoarseGrainedExecutorBackend --driver-url $SPARK_DRIVER_URL --executor-id $SPARK_EXECUTOR_ID --cores $SPARK_EXECUTOR_CORES --app-id $SPARK_APPLICATION_ID --hostname $SPARK_EXECUTOR_POD_IP --resourceProfileId $SPARK_RESOURCE_PROFILE_ID)
+ exec /usr/bin/tini -s -- /usr/local/openjdk-11/bin/java -Dspark.driver.port=7078 -Dspark.driver.blockManager.port=7079 -Xms512m -Xmx512m -cp '/opt/spark/conf::/opt/spark/jars/*:' org.apache.spark.executor.CoarseGrainedExecutorBackend --driver-url spark://CoarseGrainedScheduler@pyspark-pi-test-01179c824434413b-driver-svc.my-dev.svc:7078 --executor-id 5 --cores 2 --app-id spark-9ceff11835944e7a9aed8747a72a0112 --hostname 192.168.1.156 --resourceProfileId 0
Using Spark's default log4j profile: org/apache/spark/log4j-defaults.properties
22/07/28 09:48:18 INFO CoarseGrainedExecutorBackend: Started daemon with process name: 15@pythonpi-84d69e82443460a3-exec-5
22/07/28 09:48:18 INFO SignalUtils: Registering signal handler for TERM
22/07/28 09:48:18 INFO SignalUtils: Registering signal handler for HUP
22/07/28 09:48:18 INFO SignalUtils: Registering signal handler for INT
WARNING: An illegal reflective access operation has occurred
WARNING: Illegal reflective access by org.apache.spark.unsafe.Platform (file:/opt/spark/jars/spark-unsafe_2.12-3.1.1.jar) to constructor java.nio.DirectByteBuffer(long,int)
WARNING: Please consider reporting this to the maintainers of org.apache.spark.unsafe.Platform
WARNING: Use --illegal-access=warn to enable warnings of further illegal reflective access operations
WARNING: All illegal access operations will be denied in a future release
22/07/28 09:48:19 WARN NativeCodeLoader: Unable to load native-hadoop library for your platform... using builtin-java classes where applicable
22/07/28 09:48:19 INFO SecurityManager: Changing view acls to: 185,root
22/07/28 09:48:19 INFO SecurityManager: Changing modify acls to: 185,root
22/07/28 09:48:19 INFO SecurityManager: Changing view acls groups to: 
22/07/28 09:48:19 INFO SecurityManager: Changing modify acls groups to: 
22/07/28 09:48:19 INFO SecurityManager: SecurityManager: authentication disabled; ui acls disabled; users  with view permissions: Set(185, root); groups with view permissions: Set(); users  with modify permissions: Set(185, root); groups with modify permissions: Set()
22/07/28 09:48:20 INFO TransportClientFactory: Successfully created connection to pyspark-pi-test-01179c824434413b-driver-svc.my-dev.svc/192.168.3.121:7078 after 143 ms (0 ms spent in bootstraps)
22/07/28 09:48:20 INFO SecurityManager: Changing view acls to: 185,root
22/07/28 09:48:20 INFO SecurityManager: Changing modify acls to: 185,root
22/07/28 09:48:20 INFO SecurityManager: Changing view acls groups to: 
22/07/28 09:48:20 INFO SecurityManager: Changing modify acls groups to: 
22/07/28 09:48:20 INFO SecurityManager: SecurityManager: authentication disabled; ui acls disabled; users  with view permissions: Set(185, root); groups with view permissions: Set(); users  with modify permissions: Set(185, root); groups with modify permissions: Set()
22/07/28 09:48:20 INFO TransportClientFactory: Successfully created connection to pyspark-pi-test-01179c824434413b-driver-svc.my-dev.svc/192.168.3.121:7078 after 53 ms (0 ms spent in bootstraps)
22/07/28 09:48:20 ERROR DiskBlockManager: Failed to create local dir in /tmp/spark-local-dir-1. Ignoring this directory.
java.io.IOException: Failed to create a temp directory (under /tmp/spark-local-dir-1) after 10 attempts!
	at org.apache.spark.util.Utils$.createDirectory(Utils.scala:305)
	at org.apache.spark.storage.DiskBlockManager.$anonfun$createLocalDirs$1(DiskBlockManager.scala:145)
	at scala.collection.TraversableLike.$anonfun$flatMap$1(TraversableLike.scala:245)
	at scala.collection.IndexedSeqOptimized.foreach(IndexedSeqOptimized.scala:36)
	at scala.collection.IndexedSeqOptimized.foreach$(IndexedSeqOptimized.scala:33)
	at scala.collection.mutable.ArrayOps$ofRef.foreach(ArrayOps.scala:198)
	at scala.collection.TraversableLike.flatMap(TraversableLike.scala:245)
	at scala.collection.TraversableLike.flatMap$(TraversableLike.scala:242)
	at scala.collection.mutable.ArrayOps$ofRef.flatMap(ArrayOps.scala:198)
	at org.apache.spark.storage.DiskBlockManager.createLocalDirs(DiskBlockManager.scala:143)
	at org.apache.spark.storage.DiskBlockManager.<init>(DiskBlockManager.scala:43)
	at org.apache.spark.storage.BlockManager.<init>(BlockManager.scala:191)
	at org.apache.spark.SparkEnv$.create(SparkEnv.scala:394)
	at org.apache.spark.SparkEnv$.createExecutorEnv(SparkEnv.scala:205)
	at org.apache.spark.executor.CoarseGrainedExecutorBackend$.$anonfun$run$7(CoarseGrainedExecutorBackend.scala:442)
	at org.apache.spark.deploy.SparkHadoopUtil$$anon$1.run(SparkHadoopUtil.scala:62)
	at org.apache.spark.deploy.SparkHadoopUtil$$anon$1.run(SparkHadoopUtil.scala:61)
	at java.base/java.security.AccessController.doPrivileged(Native Method)
	at java.base/javax.security.auth.Subject.doAs(Unknown Source)
	at org.apache.hadoop.security.UserGroupInformation.doAs(UserGroupInformation.java:1746)
	at org.apache.spark.deploy.SparkHadoopUtil.runAsSparkUser(SparkHadoopUtil.scala:61)
	at org.apache.spark.executor.CoarseGrainedExecutorBackend$.run(CoarseGrainedExecutorBackend.scala:393)
	at org.apache.spark.executor.CoarseGrainedExecutorBackend$.main(CoarseGrainedExecutorBackend.scala:382)
	at org.apache.spark.executor.CoarseGrainedExecutorBackend.main(CoarseGrainedExecutorBackend.scala)
22/07/28 09:48:20 ERROR DiskBlockManager: Failed to create any local dir.
```

**Comment by jzhangConviva** [comment]
I used the HostPath as the volume and faced the same issue above. My solution is to change the mode of the local directory on the host. It works.

**Comment by ravikrddy** [comment]
You can try adding initContainers to create directory.
```
executor:
    ...
    initContainers:
    - name: create directory
      image: artifactory.wdc.com:6609/busybox:1.28
      command: ['sh', '-c', 'mkdir /tmp/spark-local-dir-1']
```
