### ISSUE TITLE
[BUG] spec.ipFamilies: field not declared in schema Exception

### ISSUE THREAD

**Issue by zhang5059T** [kubeflow/spark-operator#2048]
## Description
deploy spark-operator
helm install spark-release spark-operator/spark-operator --namespace spark --create-namespace
run example 
kubectl apply -f spark-pi.yaml

Some exceptions occurred.

 E0606 07:11:36.665800       9 controller.go:768] failed to run spark-submit for SparkApplication spark/spark-pi: failed to run spark-submit for SparkApplication spark/spark-pi: 24/06/06 07:11:34 WARN NativeCodeLoader: Unable to load native-hadoop library for your platform... using builtin-java classes where applicable
 24/06/06 07:11:34 INFO SparkKubernetesClientFactory: Auto-configuring K8S client using current context from users K8S config file
 24/06/06 07:11:34 INFO KerberosConfDriverFeatureStep: You have not specified a krb5.conf file locally or via a ConfigMap. Make sure that you have the krb5.conf locally on the driver image.
 Exception in thread "main" io.fabric8.kubernetes.client.KubernetesClientException: Failure executing: PATCH at: https://192.18.0.1:443/api/v1/namespaces/spark/services/spark-pi-358e258fec637e87-driver-svc?fieldManager=fabric8&force=true. Message: failed to create typed patch object: errors:
   .spec.ports: element 0: associative list with keys has an element that omits key field "protocol"
   .spec.ipFamilies: field not declared in schema. Received status: Status(apiVersion=v1, code=500, details=null, kind=Status, message=failed to create typed patch object: errors:
   .spec.ports: element 0: associative list with keys has an element that omits key field "protocol"
   .spec.ipFamilies: field not declared in schema, metadata=ListMeta(_continue=null, remainingItemCount=null, resourceVersion=null, selfLink=null, additionalProperties={}), reason=null, status=Failure, additionalProperties={}).
 	at io.fabric8.kubernetes.client.KubernetesClientException.copyAsCause(KubernetesClientException.java:238)
 	at io.fabric8.kubernetes.client.dsl.internal.OperationSupport.waitForResult(OperationSupport.java:518)
 	at io.fabric8.kubernetes.client.dsl.internal.OperationSupport.handleResponse(OperationSupport.java:535)
 	at io.fabric8.kubernetes.client.dsl.internal.OperationSupport.handlePatch(OperationSupport.java:430)
 	at io.fabric8.kubernetes.client.dsl.internal.OperationSupport.handlePatch(OperationSupport.java:408)
 	at io.fabric8.kubernetes.client.dsl.internal.BaseOperation.handlePatch(BaseOperation.java:713)
 	at io.fabric8.kubernetes.client.dsl.internal.HasMetadataOperation.lambda$patch$2(HasMetadataOperation.java:232)
 	at io.fabric8.kubernetes.client.dsl.internal.HasMetadataOperation.patch(HasMetadataOperation.java:237)
 	at io.fabric8.kubernetes.client.dsl.internal.HasMetadataOperation.patch(HasMetadataOperation.java:252)
 	at io.fabric8.kubernetes.client.dsl.internal.BaseOperation.serverSideApply(BaseOperation.java:1132)
 	at io.fabric8.kubernetes.client.dsl.internal.BaseOperation.serverSideApply(BaseOperation.java:92)
 	at io.fabric8.kubernetes.client.extension.ResourceAdapter.serverSideApply(ResourceAdapter.java:325)
 	at java.base/java.util.stream.ReferencePipeline$3$1.accept(Unknown Source)
 	at java.base/java.util.ArrayList$ArrayListSpliterator.forEachRemaining(Unknown Source)
 	at java.base/java.util.stream.AbstractPipeline.copyInto(Unknown Source)
 	at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(Unknown Source)
 	at java.base/java.util.stream.ReduceOps$ReduceOp.evaluateSequential(Unknown Source)
 	at java.base/java.util.stream.AbstractPipeline.evaluate(Unknown Source)
 	at java.base/java.util.stream.ReferencePipeline.collect(Unknown Source)
 	at io.fabric8.kubernetes.client.dsl.internal.NamespaceVisitFromServerGetWatchDeleteRecreateWaitApplicableListImpl.performOperation(NamespaceVisitFromServerGetWatchDeleteRecreateWaitApplicableListImpl.java:294)
 	at io.fabric8.kubernetes.client.dsl.internal.NamespaceVisitFromServerGetWatchDeleteRecreateWaitApplicableListImpl.serverSideApply(NamespaceVisitFromServerGetWatchDeleteRecreateWaitApplicableListImpl.java:324)
 	at io.fabric8.kubernetes.client.dsl.internal.NamespaceVisitFromServerGetWatchDeleteRecreateWaitApplicableListImpl.serverSideApply(NamespaceVisitFromServerGetWatchDeleteRecreateWaitApplicableListImpl.java:55)
 	at org.apache.spark.deploy.k8s.submit.Client.run(KubernetesClientApplication.scala:176)
 	at org.apache.spark.deploy.k8s.submit.KubernetesClientApplication.$anonfun$run$6(KubernetesClientApplication.scala:256)
 	at org.apache.spark.deploy.k8s.submit.KubernetesClientApplication.$anonfun$run$6$adapted(KubernetesClientApplication.scala:250)
 	at org.apache.spark.util.SparkErrorUtils.tryWithResource(SparkErrorUtils.scala:48)
 	at org.apache.spark.util.SparkErrorUtils.tryWithResource$(SparkErrorUtils.scala:46)
 	at org.apache.spark.util.Utils$.tryWithResource(Utils.scala:94)
 	at org.apache.spark.deploy.k8s.submit.KubernetesClientApplication.run(KubernetesClientApplication.scala:250)
 	at org.apache.spark.deploy.k8s.submit.KubernetesClientApplication.start(KubernetesClientApplication.scala:223)
 	at org.apache.spark.deploy.SparkSubmit.org$apache$spark$deploy$SparkSubmit$$runMain(SparkSubmit.scala:1029)
 	at org.apache.spark.deploy.SparkSubmit.doRunMain$1(SparkSubmit.scala:194)
 	at org.apache.spark.deploy.SparkSubmit.submit(SparkSubmit.scala:217)
 	at org.apache.spark.deploy.SparkSubmit.doSubmit(SparkSubmit.scala:91)
 	at org.apache.spark.deploy.SparkSubmit$$anon$2.doSubmit(SparkSubmit.scala:1120)
 	at org.apache.spark.deploy.SparkSubmit$.main(SparkSubmit.scala:1129)
 	at org.apache.spark.deploy.SparkSubmit.main(SparkSubmit.scala)

What do I need to do to avoid this exception?
## Environment & Versions

- Spark Operator App version:
- Helm Chart Version: 
version.BuildInfo{Version:"v3.2.1", GitCommit:"fe51cd1e31e6a202cba7dead9552a6d418ded79a", GitTreeState:"clean", GoVersion:"go1.13.10"}
- Kubernetes Version: 
  GitVersion:"v1.18.6"
- Apache Spark version: 
  3.3.0

**Comment by zhang5059T** [comment]
The answer is found that my Kubernetes version is too low. Are there any images suitable for the Kubernetes version of 1.18.6?

**Comment by yuchaoran2011** [comment]
K8s 1.18 is already deprecated and out of support by all major cloud providers. It's best to upgrade the k8s version of your cluster

**Comment by Amri91** [comment]
@zhang5059T I got the same error. Here is my issue: https://github.com/kubeflow/spark-operator/issues/2051

I eventually made it work by switching to the branch v1beta2-1.3.3-3.1.1 and using Apache Spark 3.4.1, as 3.5.1 did not work. I had to rebuild the operator image and update the app spark version.

**Comment by zhang5059T** [comment]
@yuchaoran2011 Upgrading the k8s cluster is a bit difficult, and this is our online environment. I'm afraid the impact range will be too wide.

**Comment by zhang5059T** [comment]
@Amri91 Thank you for providing the version. The version 3.4.1 of Spark also fits my environment very well. I will try to build the image of this version to solve this problem.
