### ISSUE TITLE
Question on spark-submit failing via the operator

### ISSUE THREAD

**Issue by jesumyip** [kubeflow/spark-operator#2208]
What does this actually mean and how can I troubleshoot this?

For context, I am using the latest release of the operator, and I use a custom base image for spark (which is based on the bitnami spark image).

There is no /home/spark folder by default in that image.

```
Warning  SparkApplicationFailed  14m   spark-application-controller  SparkApplication brazil-pan-ecs failed: failed to run spark-submit: failed to run spark-submit: Ivy Default Cache set to: /home/spark/.ivy2/cache
The jars for the packages stored in: /home/spark/.ivy2/jars
org.apache.spark#spark-streaming-kafka-0-10_2.12 added as a dependency
org.apache.spark#spark-sql-kafka-0-10_2.12 added as a dependency
:: resolving dependencies :: org.apache.spark#spark-submit-parent-511288aa-ce7c-4a38-9c8e-4869b71c68fa;1.0
  confs: [default]
Exception in thread "main" java.io.FileNotFoundException: /home/spark/.ivy2/cache/resolved-org.apache.spark-spark-submit-parent-511288aa-ce7c-4a38-9c8e-4869b71c68fa-1.0.xml (No such file or directory)
           at java.base/java.io.FileOutputStream.open0(Native Method)
           at java.base/java.io.FileOutputStream.open(Unknown Source)
           at java.base/java.io.FileOutputStream.<init>(Unknown Source)
           at java.base/java.io.FileOutputStream.<init>(Unknown Source)
           at org.apache.ivy.plugins.parser.xml.XmlModuleDescriptorWriter.write(XmlModuleDescriptorWriter.java:71)
           at org.apache.ivy.plugins.parser.xml.XmlModuleDescriptorWriter.write(XmlModuleDescriptorWriter.java:63)
           at org.apache.ivy.core.module.descriptor.DefaultModuleDescriptor.toIvyFile(DefaultModuleDescriptor.java:553)
           at org.apache.ivy.core.cache.DefaultResolutionCacheManager.saveResolvedModuleDescriptor(DefaultResolutionCacheManager.java:184)
           at org.apache.ivy.core.resolve.ResolveEngine.resolve(ResolveEngine.java:259)
           at org.apache.ivy.Ivy.resolve(Ivy.java:522)
           at org.apache.spark.deploy.SparkSubmitUtils$.resolveMavenCoordinates(SparkSubmit.scala:1580)
           at org.apache.spark.util.DependencyUtils$.resolveMavenDependencies(DependencyUtils.scala:185)
           at org.apache.spark.deploy.SparkSubmit.prepareSubmitEnvironment(SparkSubmit.scala:334)
           at org.apache.spark.deploy.SparkSubmit.org$apache$spark$deploy$SparkSubmit$$runMain(SparkSubmit.scala:964)
           at org.apache.spark.deploy.SparkSubmit.doRunMain$1(SparkSubmit.scala:194)
           at org.apache.spark.deploy.SparkSubmit.submit(SparkSubmit.scala:217)
           at org.apache.spark.deploy.SparkSubmit.doSubmit(SparkSubmit.scala:91)
           at org.apache.spark.deploy.SparkSubmit$$anon$2.doSubmit(SparkSubmit.scala:1120)
           at org.apache.spark.deploy.SparkSubmit$.main(SparkSubmit.scala:1129)
           at org.apache.spark.deploy.SparkSubmit.main(SparkSubmit.scala)
  Warning  SparkApplicationPendingRerun  44s (x2 over 50s)  spark-application-controller  SparkApplication brazil-pan-ecs is pending rerun
```

**Comment by jesumyip** [comment]
What's odd is if I manually do a `docker run` with:
```
spark-submit --name test-pan-ecs --packages org.apache.spark:spark-streaming-kafka-0-10_2.12:3.5.0,org.apache.spark:spark-sql-kafka-0-10_2.12:3.5.0 --conf spark.jars.ivy=/opt/bitnami/spark/.ivy2 /opt/bitnami/spark/universal_parser.py
```
the container starts up normally.

**Comment by missedone** [comment]
got the same error with spark-operator 2.0.1, it works with 2.0.0

**Comment by jesumyip** [comment]
@missedone thanks for the tip! I will test this out on my end.

**Comment by jesumyip** [comment]
How did you get around this? I have specified
```
  sparkConf:
    spark.jars.ivy: /opt/bitnami/spark/.ivy2
    spark.driver.extraJavaOptions: -Divy.cache.dir=/opt/bitnami/spark/.ivy2 -Divy.home=/opt/bitnami/spark/.ivy2
```
in my `SparkApplication` YAML file but you can see from the pod logs that the ivy default cache location goes to `/tmp/.ivy/cache` and completely ignores my configuration. 

I have confirmed that `spark.configuration` is correctly mounted inside the pod from a configmap created by the operator and has the correct values in it. Do I actually have to modify `ivysettings.xml` in my base image?

```
:: loading settings :: url = jar:file:/opt/bitnami/spark/jars/ivy-2.5.1.jar!/org/apache/ivy/core/settings/ivysettings.xml
Ivy Default Cache set to: /tmp/.ivy/cache
The jars for the packages stored in: /tmp/.ivy/jars
org.apache.spark#spark-streaming-kafka-0-10_2.12 added as a dependency
org.apache.spark#spark-sql-kafka-0-10_2.12 added as a dependency
:: resolving dependencies :: org.apache.spark#spark-submit-parent-f1a326af-fa2f-47c6-b83c-cf6efcf5ad2d;1.0
        confs: [default]
        found org.apache.spark#spark-streaming-kafka-0-10_2.12;3.5.1 in central
        found org.apache.spark#spark-token-provider-kafka-0-10_2.12;3.5.1 in central
        found org.apache.kafka#kafka-clients;3.4.1 in central
        found org.lz4#lz4-java;1.8.0 in central
        found org.xerial.snappy#snappy-java;1.1.10.3 in central
        found org.slf4j#slf4j-api;2.0.7 in central
        found org.apache.hadoop#hadoop-client-runtime;3.3.4 in central
```

**Comment by jesumyip** [comment]
I ended up modifying my Dockerfile to build my own image with `--conf spark.jars.ivy=/tmp/.ivy`

**Comment by jesumyip** [comment]
> got the same error with spark-operator 2.0.1, while it works with 2.0.0.
> 
> and seems it not base image specific issue, as we changed from bitnami spark image to the official spark image, the same error.
> 
> we have to rollback to 2.0.0 to unblock the team.

Yup, I can confirm 2.0.0 works just fine in my testing. @missedone
