### ISSUE TITLE
custom prometheus.yaml file

### ISSUE THREAD

**Issue by mirajgodha** [kubeflow/spark-operator#904]
You can specify the custom content of `metrics.properties` using` monitoring.metricsProperties` , and custom location of `prometheus.yaml` using `monitoring.prometheus.configFile`. One option to use a custom `prometheus.yaml` file is to mount it to your driver pod using a configmap. Another option is to build a custom Docker image.

 However, looking at the [documentation](https://github.com/GoogleCloudPlatform/spark-on-k8s-operator/blob/master/docs/user-guide.md#monitoring) it looks like: 
The field `.spec.monitoring.prometheus.configuration` specifies the content of the configuration to be used with the JMX exporter. The content of prometheus.yaml will be used by default if .spec.monitoring.prometheus.configuration is not specified.

If we can mention it here also, that will be very useful. Otherwise giving the file path on this `.spec.monitoring.prometheus.configuration` we get this error, which is difficult to debug.

`ass com.miraj.SparkStreamingFromDirectory spark-internal miraj miraj1 1580803200
Exception in thread "main" java.lang.reflect.InvocationTargetException
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at sun.instrument.InstrumentationImpl.loadClassAndStartAgent(InstrumentationImpl.java:386)
	at sun.instrument.InstrumentationImpl.loadClassAndCallPremain(InstrumentationImpl.java:401)
Caused by: java.lang.ClassCastException: java.lang.String cannot be cast to java.util.Map
	at io.prometheus.jmx.shaded.io.prometheus.jmx.JmxCollector.<init>(JmxCollector.java:74)
	at io.prometheus.jmx.shaded.io.prometheus.jmx.JavaAgent.premain(JavaAgent.java:52)
	... 6 more`

Thanks, however, it works fine with configFile

**Comment by liyinan926** [comment]
It's a bit confusing to me. What you meant by `Otherwise giving the file path on this .spec.monitoring.prometheus.configuration we get this error, which is difficult to debug`? Did you give a file path value to `.spec.monitoring.prometheus.configuration`?
